### PR TITLE
Fixed stopping of motors for penalized robots

### LINKED ISSUE #163: Motors still execute old goals after robot being sent to penalty
**Describe the Bug**
When a robot is being sent to penalty, the player controller stops accepting new positions for the motors. However, the old position goals that were sent are still being executed.

**Steps to Reproduce**
1. Start the simulator
2. Let the robot walk in
3. Move the robot to the other side
4. Change the gamestate to SET
5. see how the robot is penalized
6. observe how actuators still move to the last position that was set

**Expected behavior**
Actuators should not execute the last command. 

**Screenshots**
Current behavior:

https://user-images.githubusercontent.com/31923619/120897246-65445a00-c625-11eb-931e-d6b7987b37a2.mp4

**Proposed Solution**
The maximum velocity could be set to zero but needs to be reset to the previous value afterwards. The behavior afterwards can be seen here:

https://user-images.githubusercontent.com/31923619/120897249-683f4a80-c625-11eb-832e-a184ea088ae8.mp4

For this we applied this patch:
```
+++ b/projects/samples/contests/robocup/controllers/player/player.cpp
@@ -442,7 +442,16 @@ public:
         else
           warn(sensor_measurements, "Motor \"" + motorPID.name() + "\" not found, PID command ignored.");
       }
-    }
+    }else{
+      for (int i = 0; i < actuatorRequests.motor_positions_size(); i++) {
+        const MotorPosition motorPosition = actuatorRequests.motor_positions(i);
+        webots::Motor *motor = robot->getMotor(motorPosition.name());
+        if (motor)
+          motor->setVelocity(0.0);
+        else
+          warn(sensor_measurements, "Motor \"" + motorPosition.name() + "\" not found, position command ignored.");
+      }}
```

but it only works if more commands are being sent.

### PR DESCRIPTION
**Pull request by omichel**
Fixes #163.

### CODE REVIEW

**Comment by SammyRamone** [comment]
I get following error when compiling the controller on this branch:
```

# make player
# compiling messages.proto
# updating messages.pb.d
# updating player.d
# compiling  messages.pb.cpp
# compiling  robot_client.cpp
# compiling  player.cpp
player.cpp: In member function ‘void PlayerServer::addMotorIfNeeded(webots::Motor*)’:
player.cpp:375:54: error: no matching function for call to ‘find(std::vector<webots::Motor*>::iterator, std::vector<webots::Motor*>::iterator, webots::Motor*&)’
 d(motors.begin(), motors.end(), motor) == motors.end())  // motor not in motors
                                      ^
In file included from /usr/include/c++/7/bits/locale_facets.h:48:0,
                 from /usr/include/c++/7/bits/basic_ios.h:37,
                 from /usr/include/c++/7/ios:44,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iterator:64,
                 from /usr/include/google/protobuf/repeated_field.h:55,
                 from messages.pb.h:27,
                 from player.cpp:42:
/usr/include/c++/7/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
/usr/include/c++/7/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
player.cpp:375:54: note:   ‘__gnu_cxx::__normal_iterator<webots::Motor**, std::vector<webots::Motor*> >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
 d(motors.begin(), motors.end(), motor) == motors.end())  // motor not in motors
                                      ^
/media/marc/New/webots/resources/Makefile.include:544: recipe for target 'build/release/player.o' failed
make[1]: *** [build/release/player.o] Error 1
Makefile:20: recipe for target 'player.Makefile' failed
```

I did do a full clean build of webots. Did you maybe forget to push some changes?

**Comment by omichel** [comment]
I can compile it successfully. I will try on another system...

**Comment by SammyRamone** [comment]
> I can compile it successfully. I will try on another system...

okay. Mine is Ubuntu 18.04. We will also try it on another system.

**Comment by omichel** [comment]
I tested and it works on both Ubuntu 20.04 and Windows.

**Comment by jgueldenstein** [comment]
On Ubuntu 18.04 I get the same error.

**Comment by jgueldenstein** [comment]
adding `#include <algorithm>` fixes the compilation errors

**Comment by jgueldenstein** [comment]
@SammyRamone  and I tested this both individually and the robot gets sent to its initial position continuously but on the bright side it does not move anymore.

**Comment by omichel** [comment]
I tested with Darwin-OP robots and I cannot reproduce the behavior you describe. For me, the robots are not sent continuously to their initial position (that should happen, like before, only twice, once when moving the robot to the penalty position and once, 40 ms afterwards for stabilizing the robot). Could you describe more precisely what did you do and what did you observe, so that I can try to reproduce the problem?

Moreover, I ran the test suite on this branch and is is 100% passing.

**Comment by jgueldenstein** [comment]
We have tested it again after the merge and it seems to work correctly and the robot can not move its actuators anymore.

**Comment by omichel** [comment]
> We have tested it again after the merge and it seems to work correctly and the robot can not move its actuators anymore.

Nice. @medrimonia: shall we merge this PR then?
