### ISSUE TITLE
Webots doesn't compile on ubuntu 18.04 due to java related error

### ISSUE THREAD

**Issue by Flova** [RoboCup-Humanoid-TC/webots#146]
**Describe the Bug**
I get the following error when I build webot:
```
SWIG_generated_files/controller_wrap.cpp:178:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
compilation terminated.
Makefile:143: recipe for target 'SWIG_generated_files/controller_wrap.o' failed

```

**Steps to Reproduce**
1. Git pull (commit 40c8de452d11e7cb4690b83be1977a73c5467934)
2. git clean -xfd
3. make clean
4. sudo ./scripts/install/linux_compilation_dependencies.sh
5. make -j 12
6. This error occurs after some time

**Expected behavior**
The build should be successfull

**System**
 - Operating System: Ubuntu 18.04
 - Graphics Card: Gtx 1080 ti

**Comment by timonegk** [comment]
`unset JAVA_HOME` before `make` fixed the problem for me.
